#ifndef __DEBUG_LEDS_H
#define __DEBUG_LEDS_H

#include "stm32f3xx.h"


#define DBG_LED1_ON() HAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_PIN_SET)
#define DBG_LED1_OFF() HAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_PIN_RESET)
#define DBG_LED1_TOGGLE() HAL_GPIO_TogglePin(GPIOC, GPIO_PIN_13)

#define DBG_LED2_ON() HAL_GPIO_WritePin(GPIOC, GPIO_PIN_14, GPIO_PIN_SET)
#define DBG_LED2_OFF() HAL_GPIO_WritePin(GPIOC, GPIO_PIN_14, GPIO_PIN_RESET)
#define DBG_LED2_TOGGLE() HAL_GPIO_TogglePin(GPIOC, GPIO_PIN_14)

#define DBG_LED3_ON() HAL_GPIO_WritePin(GPIOC, GPIO_PIN_15, GPIO_PIN_SET)
#define DBG_LED3_OFF() HAL_GPIO_WritePin(GPIOC, GPIO_PIN_15, GPIO_PIN_RESET)
#define DBG_LED3_TOGGLE() HAL_GPIO_TogglePin(GPIOC, GPIO_PIN_15)

#define DBG_PIN1_ON() HAL_GPIO_WritePin(GPIOA, GPIO_PIN_0, GPIO_PIN_SET)
#define DBG_PIN1_OFF() HAL_GPIO_WritePin(GPIOA, GPIO_PIN_0, GPIO_PIN_RESET)
#define DBG_PIN1_TOGGLE() HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_0)

#define DBG_PIN2_ON() HAL_GPIO_WritePin(GPIOA, GPIO_PIN_1, GPIO_PIN_SET)
#define DBG_PIN2_OFF() HAL_GPIO_WritePin(GPIOA, GPIO_PIN_1, GPIO_PIN_RESET)
#define DBG_PIN2_TOGGLE() HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_1)

#define DBG_PIN3_ON() HAL_GPIO_WritePin(GPIOA, GPIO_PIN_6, GPIO_PIN_SET)
#define DBG_PIN3_OFF() HAL_GPIO_WritePin(GPIOA, GPIO_PIN_6, GPIO_PIN_RESET)
#define DBG_PIN3_TOGGLE() HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_6)

#define DBG_PIN4_ON() HAL_GPIO_WritePin(GPIOA, GPIO_PIN_7, GPIO_PIN_SET)
#define DBG_PIN4_OFF() HAL_GPIO_WritePin(GPIOA, GPIO_PIN_7, GPIO_PIN_RESET)
#define DBG_PIN4_TOGGLE() HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_7)

#endif